config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'stringify', to: 'pages#stringify'
  get 'age', to: 'pages#age'
  put 'age', to: 'pages#person'
  get 'me', to: 'pages#me'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/foobar.rb
class Foobar

  def initialize(param)
    @param = param
  end
  
  def bar(a, b)
    @baz = [a, @param, b.values[0]].join("")
  end
end

app/controllers/concerns/person.rb
class Person
  attr_accessor :name, :age

  def initialize(name, age)
    @name = name
    @age = age
    @nickname = name[0..3]
  end

  def nickname
    @nickname
  end

  def birth_year
    2016 - @age.to_i
  end

  def introduction
    "Name: " + @name + " Age: " + @age 
  end

  def fib_number
    n = @age.to_i
    new, old = 1, 0
    n.times {new, old = new + old, new}
    old
  end
end

app/controllers/concerns/stringify.rb
class Stringify
  attr_accessor :name, :adjective

  def initialize(name, adjective)
    @name = name
    @adjective = adjective
  end

  def what_am_i
    if @name.blank? or @adjective.blank?
      "You are nothing!"
    else 
      @name + " is so " + @adjective
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    foo = Foobar.new "baz"
    @baz = foo.bar :cat, sat: :dat, dat: :sat
  end

  def stringify
    stringify_instance = Stringify.new(
      params[:name],
      params[:adjective]
    )
    @text = stringify_instance.what_am_i
  end

  def age
  end

  def person
    @person = Person.new params[:name], params[:age]
  end
  
  def me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/age.html.erb
<h1>REROUTE ME!</h1>

app/views/pages/home.html.erb
<h1>Hello There! Welcome to homework 2!</h1>
<p>What a beautiful homepage!</p>
<p>Good thing this isn't the web design decal.</p>

<h1>Question 1</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag stringify_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name %>
  <%= label_tag :adjective, "An adjective here!" %>
  <%= text_area_tag :adjective %>
  <%= submit_tag "Stringify!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<h1>Question 2</h1>

<p>Your result</p>
<%= @baz %>

<h1>Question 3</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag age_path, method: :put do %>
  <%= label_tag :name, "Your name:" %>
  <%= text_area_tag :name %>
  <%= label_tag :age, "Your age:" %>
  <%= text_area_tag :age %>
  <%= submit_tag "Submit!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

app/views/pages/me.html.erb
<center><h1>Name: Zhitong Qiu</h1>
<br/>



<img src="assets/images/Me.JPG" alt="Pic of Self" style="width:304px;height:228px;">
<br/>

<h2>Place: Los Angeles, CA</h2>
<br/>

<h2>Year: Junior</h2>
<br/>

<fun><b>Fun Fact: I still don't know how to swim ):</b></fun>

<p><u>I am just excited to learn the magic of Ruby on Rails!</u></p>
</center>

app/views/pages/person.html.erb
<h1>Name: </h1>
<%= @person.name %>
<br/>
<h1>Introduction: </h1>
<%= @person.introduction %>
<br/>
<h1>Nickname: </h1>
<%= @person.nickname %>
<br />
<h1>Birth year: </h1>
<%= @person.birth_year %>
<br />
<h1>Fib number</h1>
<%= @person.fib_number %>

app/views/pages/stringify.html.erb
<%= @text %>